### Get All Profiles
GET localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbmpvbkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwiaWQiOiJiM2UzN2Y2YS0xYTczLTRjNGQtYjNiMi1lYzYxYTdmMWUwZjIiLCJpYXQiOjE3NjA5NzcxMjIsImV4cCI6MTc2MTA2MzUyMn0.Ko8wpd_To3jGt0VsXGydMpdKrj04hUsFIslKsdSn6dA

### Get Profile by ID
GET localhost:8080/api/v1/profile/ada86df2-0c6a-4e4a-ad99-99d361af8093
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbmpvbkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwiaWQiOiJiM2UzN2Y2YS0xYTczLTRjNGQtYjNiMi1lYzYxYTdmMWUwZjIiLCJpYXQiOjE3NjA5NzcxMjIsImV4cCI6MTc2MTA2MzUyMn0.Ko8wpd_To3jGt0VsXGydMpdKrj04hUsFIslKsdSn6dA

### Change Status
PUT localhost:8080/api/v1/profile/status/9dd9f403-f3f4-4bb6-9f65-b025113560a0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbmpvbkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwiaWQiOiJiM2UzN2Y2YS0xYTczLTRjNGQtYjNiMi1lYzYxYTdmMWUwZjIiLCJpYXQiOjE3NjA5NzcxMjIsImV4cCI6MTc2MTA2MzUyMn0.Ko8wpd_To3jGt0VsXGydMpdKrj04hUsFIslKsdSn6dA

{
  "status": "BLOCKED"
}

### Delete Profile
DELETE localhost:8080/api/v1/profile/delete/9dd9f403-f3f4-4bb6-9f65-b025113560a0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbmpvbkBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwiaWQiOiJiM2UzN2Y2YS0xYTczLTRjNGQtYjNiMi1lYzYxYTdmMWUwZjIiLCJpYXQiOjE3NjA5NzcxMjIsImV4cCI6MTc2MTA2MzUyMn0.Ko8wpd_To3jGt0VsXGydMpdKrj04hUsFIslKsdSn6dA
